import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import './globals.scss'
import { Providers } from './providers'
import { Toaster } from 'sonner'

const zen = Noto_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Middle Level Authorization',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={zen.className}>
        <Providers>
          {children}
          <Toaster theme="dark" position="bottom-right" duration={1500} />
        </Providers>
      </body>
    </html>
  )
}
